//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class password_resets
    {
        public string email { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
