//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class technology_user
    {
        public int user_id { get; set; }
        public int technology_id { get; set; }
    }
}
